// <auto-generated />
using System;
using BarcelonaPulse.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarcelonaPulse.Api.Infrastructure.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    [Migration("20261006080459_Retention")]
    partial class Retention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Ingestion.IngestionRejection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detail");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingestion_run_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<string>("RecordKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_kind");

                    b.Property<string>("RecordRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("record_ref");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_rejections");

                    b.HasIndex("IngestionRunId")
                        .HasDatabaseName("ix_ingestion_rejections_ingestion_run_id");

                    b.ToTable("ingestion_rejections", (string)null);
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Ingestion.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adapter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adapter");

                    b.Property<string>("AdapterVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adapter_version");

                    b.Property<DateTimeOffset?>("CoveredFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("covered_from");

                    b.Property<DateTimeOffset?>("CoveredTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("covered_to");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("input_ref");

                    b.Property<string>("InputSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_sha256");

                    b.Property<int>("ObservationsAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("observations_accepted");

                    b.Property<int>("ObservationsConflicting")
                        .HasColumnType("integer")
                        .HasColumnName("observations_conflicting");

                    b.Property<int>("ObservationsDuplicate")
                        .HasColumnType("integer")
                        .HasColumnName("observations_duplicate");

                    b.Property<int>("ObservationsReceived")
                        .HasColumnType("integer")
                        .HasColumnName("observations_received");

                    b.Property<int>("ObservationsRejected")
                        .HasColumnType("integer")
                        .HasColumnName("observations_rejected");

                    b.Property<DateTimeOffset?>("PeriodFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_from");

                    b.Property<DateTimeOffset?>("PeriodTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_to");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("StationVersionsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("station_versions_created");

                    b.Property<int>("StationsReceived")
                        .HasColumnType("integer")
                        .HasColumnName("stations_received");

                    b.Property<int>("StationsRejected")
                        .HasColumnType("integer")
                        .HasColumnName("stations_rejected");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_runs");

                    b.HasIndex("SourceId", "StartedAt")
                        .HasDatabaseName("ix_ingestion_runs_source_id_started_at");

                    b.ToTable("ingestion_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingestion_runs_covered", "(covered_from IS NULL AND covered_to IS NULL) OR covered_from < covered_to");

                            t.HasCheckConstraint("ck_ingestion_runs_status", "status IN ('running', 'succeeded', 'succeeded_with_issues', 'failed')");
                        });
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Sources.DataSource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attribution");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("License")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("license");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("ObservationCount")
                        .HasColumnType("bigint")
                        .HasColumnName("observation_count");

                    b.Property<TimeSpan>("StalenessTolerance")
                        .HasColumnType("interval")
                        .HasColumnName("staleness_tolerance");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.ToTable("data_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_data_sources_kind", "kind IN ('observed', 'synthetic')");

                            t.HasCheckConstraint("ck_data_sources_tolerance", "staleness_tolerance > interval '0'");
                        });
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Stations.Station", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceStationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_station_id");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("SourceId", "SourceStationId")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_source_id_source_station_id");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Stations.StationObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BikesAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("bikes_available");

                    b.Property<int?>("BikesDisabled")
                        .HasColumnType("integer")
                        .HasColumnName("bikes_disabled");

                    b.Property<int?>("DocksAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("docks_available");

                    b.Property<int?>("DocksDisabled")
                        .HasColumnType("integer")
                        .HasColumnName("docks_disabled");

                    b.Property<int?>("EbikesAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("ebikes_available");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingestion_run_id");

                    b.Property<bool?>("IsRenting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_renting");

                    b.Property<bool?>("IsReturning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_returning");

                    b.Property<int?>("MechanicalBikesAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("mechanical_bikes_available");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.PrimitiveCollection<string[]>("QualityFlags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("quality_flags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_station_observations");

                    b.HasIndex("IngestionRunId")
                        .HasDatabaseName("ix_station_observations_ingestion_run_id");

                    b.HasIndex("StationId", "ObservedAt")
                        .IsUnique()
                        .HasDatabaseName("ux_station_observations_station_observed_at");

                    b.ToTable("station_observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_station_observations_counts", "(bikes_available IS NULL OR bikes_available >= 0) AND (mechanical_bikes_available IS NULL OR mechanical_bikes_available >= 0) AND (ebikes_available IS NULL OR ebikes_available >= 0) AND (docks_available IS NULL OR docks_available >= 0) AND (bikes_disabled IS NULL OR bikes_disabled >= 0) AND (docks_disabled IS NULL OR docks_disabled >= 0)");

                            t.HasCheckConstraint("ck_station_observations_status", "status IN ('in_service', 'maintenance', 'closed', 'planned', 'unknown')");
                        });
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Stations.StationVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingestion_run_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Neighbourhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("neighbourhood");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint")
                        .HasColumnName("station_id");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_station_versions");

                    b.HasIndex("IngestionRunId")
                        .HasDatabaseName("ix_station_versions_ingestion_run_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_station_versions_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("StationId")
                        .IsUnique()
                        .HasDatabaseName("ix_station_versions_one_current_per_station")
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("station_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_station_versions_capacity", "capacity IS NULL OR capacity >= 0");

                            t.HasCheckConstraint("ck_station_versions_validity", "valid_from IS NULL OR valid_to IS NULL OR valid_from < valid_to");
                        });
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Ingestion.IngestionRejection", b =>
                {
                    b.HasOne("BarcelonaPulse.Api.Features.Ingestion.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_rejections_ingestion_runs_ingestion_run_id");
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Ingestion.IngestionRun", b =>
                {
                    b.HasOne("BarcelonaPulse.Api.Features.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_runs_data_sources_source_id");
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Stations.Station", b =>
                {
                    b.HasOne("BarcelonaPulse.Api.Features.Sources.DataSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stations_data_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Stations.StationObservation", b =>
                {
                    b.HasOne("BarcelonaPulse.Api.Features.Ingestion.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_station_observations_ingestion_runs_ingestion_run_id");

                    b.HasOne("BarcelonaPulse.Api.Features.Stations.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_observations_stations_station_id");
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Stations.StationVersion", b =>
                {
                    b.HasOne("BarcelonaPulse.Api.Features.Ingestion.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_station_versions_ingestion_runs_ingestion_run_id");

                    b.HasOne("BarcelonaPulse.Api.Features.Stations.Station", "Station")
                        .WithMany("Versions")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_versions_stations_station_id");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("BarcelonaPulse.Api.Features.Stations.Station", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
