/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fuentes de datos, su tipo (observada o sintética) y el periodo que cubren */
    get: operations['ListSources'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Estaciones de una fuente y su estado en un instante
     * @description Devuelve la versión vigente de cada estación y su última observación anterior o igual a `at`. Fuera de la tolerancia de la fuente el estado es `unknown` y los recuentos son nulos.
     */
    get: operations['ListStations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Una estación, su estado en un instante y sus versiones */
    get: operations['GetStation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Frescura del dato en el instante consultado.
     * @enum {unknown}
     */
    Freshness: 'current' | 'stale' | 'none';
    HttpValidationProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      errors?: {
        [key: string]: string[];
      };
    };
    /** @enum {unknown} */
    IngestionStatus: 'running' | 'succeeded' | 'succeeded_with_rejections' | 'failed';
    /**
     * @description Cómo se eligió el instante de la respuesta.
     * @enum {unknown}
     */
    InstantBasis: 'requested' | 'latest_observation' | 'now';
    LastIngestionSummary: {
      /** Format: date-time */
      startedAt: string;
      /** Format: date-time */
      finishedAt: null | string;
      status: components['schemas']['IngestionStatus'];
      /** Format: int32 */
      observationsAccepted: number;
      /** Format: int32 */
      observationsDuplicate: number;
      /** Format: int32 */
      observationsRejected: number;
    };
    ObservationPeriod: {
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
      /** Format: int64 */
      observationCount: number;
    };
    /** @enum {unknown} */
    ObservationStatus: 'in_service' | 'maintenance' | 'closed' | 'planned' | 'unknown';
    ProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
    };
    /** @enum {unknown} */
    SourceKind: 'observed' | 'synthetic';
    SourceRef: {
      id: string;
      kind: components['schemas']['SourceKind'];
      name: string;
      attribution: string;
      license: null | string;
      url: null | string;
    };
    /** @description Fuente disponible, con el periodo realmente cubierto por sus observaciones. */
    SourceSummary: {
      id: string;
      kind: components['schemas']['SourceKind'];
      name: string;
      attribution: string;
      license: null | string;
      url: null | string;
      /** Format: int32 */
      toleranceMinutes: number;
      /** Format: int32 */
      stationCount: number;
      period: null | components['schemas']['ObservationPeriod'];
      lastIngestion: null | components['schemas']['LastIngestionSummary'];
    };
    StationDetailResponse: {
      source: components['schemas']['SourceRef'];
      /** Format: date-time */
      at: string;
      atBasis: components['schemas']['InstantBasis'];
      /** Format: int32 */
      toleranceMinutes: number;
      station: components['schemas']['StationItem'];
      versions: components['schemas']['StationVersionItem'][];
    };
    /** @description Estación con sus atributos vigentes en el instante consultado. */
    StationItem: {
      /**
       * Format: int64
       * @description Identificador interno, estable dentro de esta base de datos.
       */
      id: number;
      /** @description Identificador tal como lo publica la fuente. */
      sourceStationId: string;
      /** @description Nombre publicado por la fuente. */
      name: string;
      /** @description Dirección, si la fuente la publica. */
      address: null | string;
      /**
       * Format: double
       * @description Longitud WGS84.
       */
      longitude: number;
      /**
       * Format: double
       * @description Latitud WGS84.
       */
      latitude: number;
      /**
       * Format: int32
       * @description Capacidad publicada; nula si la fuente no la da.
       */
      capacity: null | number;
      /**
       * @description Los atributos se publicaron después del instante consultado y se asumen vigentes
       *     también antes (primera versión conocida).
       */
      metadataAssumed: boolean;
      /** @description Estado en el instante consultado. */
      state: components['schemas']['StationState'];
    };
    StationsResponse: {
      source: components['schemas']['SourceRef'];
      /** Format: date-time */
      at: string;
      atBasis: components['schemas']['InstantBasis'];
      /** Format: int32 */
      toleranceMinutes: number;
      /** Format: int32 */
      count: number;
      truncated: boolean;
      stations: components['schemas']['StationItem'][];
    };
    /**
     * @description Estado en el instante consultado. Si la frescura no es `current`, el estado es
     *     `unknown` y los recuentos son nulos: falta de dato no es cero.
     */
    StationState: {
      freshness: components['schemas']['Freshness'];
      /** Format: date-time */
      lastObservedAt: null | string;
      status: components['schemas']['ObservationStatus'];
      /** Format: int32 */
      bikesAvailable: null | number;
      /** Format: int32 */
      mechanicalBikesAvailable: null | number;
      /** Format: int32 */
      ebikesAvailable: null | number;
      /** Format: int32 */
      docksAvailable: null | number;
      /** Format: int32 */
      bikesDisabled: null | number;
      /** Format: int32 */
      docksDisabled: null | number;
      qualityFlags: string[];
    };
    StationVersionItem: {
      name: string;
      address: null | string;
      /** Format: double */
      longitude: number;
      /** Format: double */
      latitude: number;
      /** Format: int32 */
      capacity: null | number;
      /** Format: date-time */
      validFrom: null | string;
      /** Format: date-time */
      validTo: null | string;
      /** Format: date-time */
      firstSeenAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ListSources: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceSummary'][];
        };
      };
    };
  };
  ListStations: {
    parameters: {
      query?: {
        /** @description Obligatorio. Identificador de la fuente (ver GET /api/sources). */
        source?: string;
        /** @description Opcional. Zona minLon,minLat,maxLon,maxLat en grados WGS84 (máximo 1° de lado). */
        bbox?: string;
        /** @description Opcional. Instante ISO 8601 con zona explícita. Sin él: fuente sintética, final de sus datos; fuente observada, ahora. La respuesta lo indica en atBasis. */
        at?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StationsResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetStation: {
    parameters: {
      query?: {
        /** @description Opcional. Instante ISO 8601 con zona explícita. Sin él: fuente sintética, final de sus datos; fuente observada, ahora. La respuesta lo indica en atBasis. */
        at?: string;
      };
      header?: never;
      path: {
        /** @description Identificador interno de la estación. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StationDetailResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
}
