/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fuentes de datos, su tipo (observada o sintética) y el periodo que cubren */
    get: operations['ListSources'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sources/{id}/ingestions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ingestas terminadas de una fuente: periodo cubierto, recuentos y rechazos por motivo
     * @description Solo las que han terminado y dicen qué periodo cubren (un día del histórico), en orden de periodo. Las purgadas se conservan con la fecha de la purga. Repetir una importación no duplica: sale como repetidas.
     */
    get: operations['ListIngestions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sources/{id}/timeline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Línea temporal de una fuente: estaciones con dato y totales en cada paso
     * @description Aplica en cada paso la misma regla que GET /api/stations: última observación ≤ instante dentro de la tolerancia. Los huecos se ven como pasos con menos estaciones con dato. Máximo 7 días por petición.
     */
    get: operations['GetTimeline'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sources/{id}/frames': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fotogramas: el estado de todas las estaciones en 12 pasos seguidos
     * @description Cada paso aplica la misma regla que GET /api/stations?at=…. Con el paso de 5 min, una hora por petición: sirve para reproducir sin una petición por paso.
     */
    get: operations['GetFrames'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/study-areas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Áreas de estudio para la cobertura: Barcelona y sus 10 distritos */
    get: operations['ListStudyAreas'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/scenarios/coverage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cobertura geométrica de la red real y de un escenario con estaciones hipotéticas
     * @description Círculos del radio elegido alrededor de cada estación, unidos y recortados al área de estudio, medidos en EPSG:25831. Devuelve el modelo, sus supuestos y los parámetros. No se guarda nada y no dice nada de demanda, viajes ni esperas.
     */
    post: operations['ComputeCoverage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Estaciones de una fuente y su estado en un instante
     * @description Devuelve la versión vigente de cada estación y su última observación anterior o igual a `at`. Fuera de la tolerancia de la fuente el estado es `unknown` y los recuentos son nulos.
     */
    get: operations['ListStations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Una estación, su estado en un instante y sus versiones */
    get: operations['GetStation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stations/{id}/pattern': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cómo estuvo una estación a cada hora en los días importados
     * @description Su estado cada 15 minutos de cada día importado de su fuente, con la misma regla que el mapa, contado por hora (de Barcelona) en laborables y en fines de semana. Es lo que pasó, no una previsión; los pasos sin dato van en `unknown`, no como cero.
     */
    get: operations['GetStationPattern'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Qué le pasa a una estación en el escenario.
     * @enum {unknown}
     */
    ChangeKind: 'added' | 'moved' | 'removed';
    /** @description Lo que el escenario cubre y la base no, y al revés. */
    CoverageDifference: {
      /** Format: double */
      gainedSquareMeters: number;
      /** Format: double */
      lostSquareMeters: number;
    };
    /** @description Geometrías GeoJSON en WGS84 (lon, lat), simplificadas 1 m para dibujarlas. */
    CoverageGeometries: {
      /** @description Área de estudio. */
      studyArea: components['schemas']['JsonElement'];
      /** @description Superficie cubierta por la red base. */
      base: components['schemas']['JsonElement'];
      /** @description Superficie cubierta por el escenario. */
      scenario: components['schemas']['JsonElement'];
      /** @description Lo que cubre el escenario y la base no. */
      gained: components['schemas']['JsonElement'];
      /** @description Lo que cubre la base y el escenario no. */
      lost: components['schemas']['JsonElement'];
      /** @description Círculo de cada estación nueva, movida o quitada, en ese orden y en el de la petición; sin simplificar. */
      reach: components['schemas']['CoverageReach'][];
    };
    /** @description Modelo con el que se ha calculado: nombre, versión y supuestos explícitos. */
    CoverageModel: {
      name: string;
      /** Format: int32 */
      version: number;
      assumptions: string[];
    };
    /**
     * @description Alcance de una estación que cambia: su círculo entero, sin recortar al área de estudio. La
     *     nueva y la movida, en su sitio del escenario; la quitada, en el de la red base.
     */
    CoverageReach: {
      /** @description Nueva, movida o quitada. */
      kind: components['schemas']['ChangeKind'];
      /** @description Etiqueta de la estación nueva (h1…); null en las reales. */
      added: null | string;
      /**
       * Format: int64
       * @description Estación real movida o quitada; null en las nuevas.
       */
      station: null | number;
      /**
       * Format: double
       * @description Parte del círculo dentro del área de estudio, al metro cuadrado.
       */
      squareMetersInArea: number;
      /** @description El mismo polígono del cálculo (64 lados), en GeoJSON WGS84. */
      circle: components['schemas']['JsonElement'];
    };
    /** @description Red base: de qué fuente, en qué instante y cuántas estaciones. */
    CoverageReference: {
      source: components['schemas']['SourceRef'];
      /** Format: date-time */
      at: string;
      atBasis: components['schemas']['InstantBasis'];
      /** Format: int32 */
      stations: number;
    };
    /** @description Escenario: la red real en un instante, con estaciones añadidas, movidas o quitadas. */
    CoverageRequest: {
      /** @description Fuente de la red base. */
      source: string;
      /** @description Área de estudio (GET /api/study-areas): el denominador del porcentaje. */
      studyArea: string;
      /**
       * Format: int32
       * @description Radio en metros, en línea recta, de 50 a 1000.
       */
      radiusMeters: number;
      /** @description Instante de referencia (ISO 8601 con zona): entran las estaciones con ubicación vigente entonces. Sin él, como en /api/stations. */
      at?: null | string;
      /** @description Estaciones hipotéticas. */
      added?: null | components['schemas']['HypotheticalStation'][];
      /** @description Estaciones reales en otra ubicación. */
      moved?: null | components['schemas']['MovedStation'][];
      /** @description Estaciones reales que no están en el escenario. */
      removed?: null | number[];
    };
    /** @description Resultado de un escenario, con todo lo necesario para reproducirlo. */
    CoverageResponse: {
      model: components['schemas']['CoverageModel'];
      reference: components['schemas']['CoverageReference'];
      studyArea: components['schemas']['StudyAreaItem'];
      /** Format: int32 */
      radiusMeters: number;
      added: components['schemas']['HypotheticalStation'][];
      moved: components['schemas']['MovedStation'][];
      removed: number[];
      base: components['schemas']['CoverageResult'];
      scenario: components['schemas']['CoverageResult'];
      difference: components['schemas']['CoverageDifference'];
      geometries: components['schemas']['CoverageGeometries'];
    };
    /** @description Superficie cubierta: la unión de los círculos, recortada al área de estudio. */
    CoverageResult: {
      /**
       * Format: int32
       * @description Estaciones que entran en el cálculo.
       */
      stations: number;
      /**
       * Format: double
       * @description Metros cuadrados del área de estudio a menos del radio de alguna estación.
       */
      coveredSquareMeters: number;
      /**
       * Format: double
       * @description Proporción del área de estudio (0 a 1).
       */
      coveredShare: number;
    };
    /** @description Un paso: las estaciones con versión vigente en ese instante y su estado. */
    Frame: {
      /** Format: date-time */
      at: string;
      states: components['schemas']['FrameState'][];
    };
    /** @description Fotogramas seguidos de una fuente. */
    FramesResponse: {
      /** @description Fuente consultada, con su tipo. */
      source: components['schemas']['SourceRef'];
      /**
       * Format: date-time
       * @description Primer paso, alineado a la rejilla (UTC).
       */
      from: string;
      /**
       * Format: int32
       * @description Minutos entre pasos.
       */
      stepMinutes: number;
      /**
       * Format: int32
       * @description Antigüedad máxima de una observación para contar como dato.
       */
      toleranceMinutes: number;
      /** @description Si había más estaciones que el máximo por respuesta. */
      truncated: boolean;
      /** @description Atributos de las estaciones, una vez para todos los pasos. */
      stations: components['schemas']['FrameStation'][];
      /** @description Los pasos, en orden. */
      frames: components['schemas']['Frame'][];
    };
    /** @description Estado de una estación en un paso. */
    FrameState: {
      /**
       * Format: int32
       * @description Posición de la estación en `stations`.
       */
      station: number;
      /** @description Estado en ese instante, con la misma regla que GET /api/stations. */
      state: components['schemas']['StationState'];
    };
    /** @description Atributos de una estación durante la ventana: una entrada por versión vigente en algún paso. */
    FrameStation: {
      /**
       * Format: int64
       * @description Identificador interno de la estación (el mismo en todas sus versiones).
       */
      id: number;
      /** @description Identificador tal como lo publica la fuente. */
      sourceStationId: string;
      /** @description Nombre publicado por la fuente. */
      name: string;
      /** @description Dirección, si la fuente la publica. */
      address: null | string;
      /** @description Distrito, si la fuente lo publica. */
      district: null | string;
      /** @description Barrio, si la fuente lo publica. */
      neighbourhood: null | string;
      /**
       * Format: double
       * @description Longitud WGS84.
       */
      longitude: number;
      /**
       * Format: double
       * @description Latitud WGS84.
       */
      latitude: number;
      /**
       * Format: int32
       * @description Capacidad publicada; nula si la fuente no la da.
       */
      capacity: null | number;
      /**
       * Format: date-time
       * @description Si es la primera versión conocida, cuándo se publicó: en los pasos anteriores sus atributos se
       *     asumen (lo mismo que `metadataAssumed` en GET /api/stations). Nulo en las demás.
       */
      assumedUntil: null | string;
    };
    /**
     * @description Frescura del dato en el instante consultado.
     * @enum {unknown}
     */
    Freshness: 'current' | 'stale' | 'none';
    HttpValidationProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      errors?: {
        [key: string]: string[];
      };
    };
    /** @description Estación inventada para el escenario. No se guarda en ningún sitio. */
    HypotheticalStation: {
      /** @description Etiqueta que pone el cliente (h1, h2…); se devuelve tal cual. */
      id: string;
      /**
       * Format: double
       * @description Longitud WGS84.
       */
      longitude: number;
      /**
       * Format: double
       * @description Latitud WGS84.
       */
      latitude: number;
    };
    /** @description Una ingesta terminada con el periodo que decía cubrir (un día del histórico). */
    IngestionItem: {
      /**
       * Format: int64
       * @description Identificador de la ejecución.
       */
      id: number;
      /**
       * Format: date-time
       * @description Cuándo empezó.
       */
      startedAt: string;
      /**
       * Format: date-time
       * @description Cuándo acabó.
       */
      finishedAt: null | string;
      /** @description Cómo acabó: bien, con incidencias (rechazos o conflictos) o fallida. */
      status: components['schemas']['IngestionStatus'];
      /**
       * Format: date-time
       * @description Inicio del periodo que cubre la entrada.
       */
      coveredFrom: string;
      /**
       * Format: date-time
       * @description Fin (excluido) del periodo que cubre la entrada.
       */
      coveredTo: string;
      /** @description Días (hora de Barcelona) de ese periodo. */
      days: string[];
      /**
       * Format: date-time
       * @description Cuándo se quitaron sus días con `purge`; nulo si siguen.
       */
      purgedAt: null | string;
      /**
       * Format: int32
       * @description Registros de estación leídos.
       */
      stationsReceived: number;
      /**
       * Format: int32
       * @description Registros de estación rechazados.
       */
      stationsRejected: number;
      /**
       * Format: int32
       * @description Versiones de estación nuevas.
       */
      stationVersionsCreated: number;
      /**
       * Format: int32
       * @description Observaciones leídas.
       */
      observationsReceived: number;
      /**
       * Format: int32
       * @description Observaciones nuevas guardadas.
       */
      observationsAccepted: number;
      /**
       * Format: int32
       * @description Repetidas: ya estaban, con los mismos valores.
       */
      observationsDuplicate: number;
      /**
       * Format: int32
       * @description En conflicto: ya estaban, con otros valores; se conservó la primera.
       */
      observationsConflicting: number;
      /**
       * Format: int32
       * @description Observaciones rechazadas.
       */
      observationsRejected: number;
      /** @description Rechazos agrupados por tipo de registro y motivo. Se guardan como máximo 1000 por ingesta: los totales son los recuentos de arriba. */
      rejections: components['schemas']['RejectionGroup'][];
    };
    /** @description Las ingestas terminadas de una fuente: lo que entró, lo que se repitió y lo que no entró, y por qué. */
    IngestionsResponse: {
      source: components['schemas']['SourceRef'];
      ingestions: components['schemas']['IngestionItem'][];
    };
    /** @enum {unknown} */
    IngestionStatus: 'running' | 'succeeded' | 'succeeded_with_issues' | 'failed';
    /**
     * @description Cómo se eligió el instante de la respuesta.
     * @enum {unknown}
     */
    InstantBasis: 'requested' | 'latest_observation' | 'now';
    JsonElement: unknown;
    LastIngestionSummary: {
      /** Format: date-time */
      startedAt: string;
      /** Format: date-time */
      finishedAt: null | string;
      status: components['schemas']['IngestionStatus'];
      /** Format: int32 */
      observationsAccepted: number;
      /** Format: int32 */
      observationsDuplicate: number;
      /** Format: int32 */
      observationsConflicting: number;
      /** Format: int32 */
      observationsRejected: number;
    };
    /** @description Estación real de la red base que en el escenario está en otro sitio. */
    MovedStation: {
      /**
       * Format: int64
       * @description Identificador interno de la estación.
       */
      station: number;
      /**
       * Format: double
       * @description Nueva longitud WGS84.
       */
      longitude: number;
      /**
       * Format: double
       * @description Nueva latitud WGS84.
       */
      latitude: number;
    };
    ObservationPeriod: {
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
      /** Format: int64 */
      observationCount: number;
    };
    /** @enum {unknown} */
    ObservationStatus: 'in_service' | 'maintenance' | 'closed' | 'planned' | 'unknown';
    /**
     * @description Laborable (de lunes a viernes; los festivos cuentan como laborables) o fin de semana.
     * @enum {unknown}
     */
    PatternDayType: 'weekday' | 'weekend';
    /**
     * @description Una hora del día (hora de Barcelona) en un tipo de día: en cuántos pasos de los días
     *     importados estuvo la estación en cada estado. Sin dato no es cero: va en `Unknown`.
     */
    PatternHour: {
      dayType: components['schemas']['PatternDayType'];
      /** Format: int32 */
      hour: number;
      /** Format: int32 */
      steps: number;
      /** Format: int32 */
      unknown: number;
      /** Format: int32 */
      outOfService: number;
      /** Format: int32 */
      empty: number;
      /** Format: int32 */
      few: number;
      /** Format: int32 */
      available: number;
      /** Format: int32 */
      full: number;
      /** Format: int32 */
      medianBikes: null | number;
    };
    ProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
    };
    /** @description Cuántos registros de un tipo se rechazaron por un motivo. */
    RejectionGroup: {
      /** @description `station`, `observation` o `input`. */
      recordKind: string;
      /** @description Motivo, tal como lo registra la ingesta (`outside_service_area`, `negative_count`…). */
      reason: string;
      /**
       * Format: int32
       * @description Registros rechazados por ese motivo.
       */
      count: number;
    };
    /** @enum {unknown} */
    SourceKind: 'observed' | 'synthetic';
    SourceRef: {
      id: string;
      kind: components['schemas']['SourceKind'];
      name: string;
      attribution: string;
      license: null | string;
      url: null | string;
    };
    /** @description Fuente disponible, con el periodo realmente cubierto por sus observaciones. */
    SourceSummary: {
      /** @description Identificador de la fuente. */
      id: string;
      /** @description Observada o sintética. */
      kind: components['schemas']['SourceKind'];
      /** @description Nombre de la fuente. */
      name: string;
      /** @description Atribución exigida por la licencia. */
      attribution: string;
      /** @description Licencia de los datos, si la hay. */
      license: null | string;
      /** @description Página del conjunto de datos, si la hay. */
      url: null | string;
      /**
       * Format: int32
       * @description Antigüedad máxima de una observación para contar como dato.
       */
      toleranceMinutes: number;
      /**
       * Format: int32
       * @description Estaciones conocidas.
       */
      stationCount: number;
      period: null | components['schemas']['ObservationPeriod'];
      /** @description Días (hora de Barcelona) que cubren sus ingestas terminadas, en orden: los que se pueden reproducir. */
      days: string[];
      lastIngestion: null | components['schemas']['LastIngestionSummary'];
    };
    StationDetailResponse: {
      source: components['schemas']['SourceRef'];
      /** Format: date-time */
      at: string;
      atBasis: components['schemas']['InstantBasis'];
      /** Format: int32 */
      toleranceMinutes: number;
      station: components['schemas']['StationItem'];
      versions: components['schemas']['StationVersionItem'][];
    };
    /** @description Estación con sus atributos vigentes en el instante consultado. */
    StationItem: {
      /**
       * Format: int64
       * @description Identificador interno, estable dentro de esta base de datos.
       */
      id: number;
      /** @description Identificador tal como lo publica la fuente. */
      sourceStationId: string;
      /** @description Nombre publicado por la fuente. */
      name: string;
      /** @description Dirección, si la fuente la publica. */
      address: null | string;
      /** @description Distrito, si la fuente lo publica. */
      district: null | string;
      /** @description Barrio, si la fuente lo publica. */
      neighbourhood: null | string;
      /**
       * Format: double
       * @description Longitud WGS84.
       */
      longitude: number;
      /**
       * Format: double
       * @description Latitud WGS84.
       */
      latitude: number;
      /**
       * Format: int32
       * @description Capacidad publicada; nula si la fuente no la da.
       */
      capacity: null | number;
      /**
       * @description Los atributos se publicaron después del instante consultado y se asumen vigentes
       *     también antes (primera versión conocida).
       */
      metadataAssumed: boolean;
      /** @description Estado en el instante consultado. */
      state: components['schemas']['StationState'];
    };
    /**
     * @description Cómo estuvo una estación a cada hora en los días importados de su fuente. Es lo que pasó, no
     *     una previsión: cada paso sigue la regla del mapa (ADR 0005) y la precedencia de la leyenda.
     */
    StationPatternResponse: {
      source: components['schemas']['SourceRef'];
      /** Format: int64 */
      stationId: number;
      sourceStationId: string;
      /** Format: int32 */
      stepMinutes: number;
      /** Format: int32 */
      toleranceMinutes: number;
      /** Format: int32 */
      fewBikesMax: number;
      weekdays: string[];
      weekendDays: string[];
      hours: components['schemas']['PatternHour'][];
    };
    StationsResponse: {
      source: components['schemas']['SourceRef'];
      /** Format: date-time */
      at: string;
      atBasis: components['schemas']['InstantBasis'];
      /** Format: int32 */
      toleranceMinutes: number;
      /** Format: int32 */
      count: number;
      truncated: boolean;
      stations: components['schemas']['StationItem'][];
    };
    /**
     * @description Estado en el instante consultado. Si la frescura no es `current`, el estado es
     *     `unknown` y los recuentos son nulos: falta de dato no es cero.
     */
    StationState: {
      freshness: components['schemas']['Freshness'];
      /** Format: date-time */
      lastObservedAt: null | string;
      status: components['schemas']['ObservationStatus'];
      /** Format: int32 */
      bikesAvailable: null | number;
      /** Format: int32 */
      mechanicalBikesAvailable: null | number;
      /** Format: int32 */
      ebikesAvailable: null | number;
      /** Format: int32 */
      docksAvailable: null | number;
      /** Format: int32 */
      bikesDisabled: null | number;
      /** Format: int32 */
      docksDisabled: null | number;
      isRenting: null | boolean;
      isReturning: null | boolean;
      qualityFlags: string[];
    };
    StationVersionItem: {
      name: string;
      address: null | string;
      district: null | string;
      neighbourhood: null | string;
      /** Format: double */
      longitude: number;
      /** Format: double */
      latitude: number;
      /** Format: int32 */
      capacity: null | number;
      /** Format: date-time */
      validFrom: null | string;
      /** Format: date-time */
      validTo: null | string;
      /** Format: date-time */
      firstSeenAt: string;
    };
    /** @description Área de estudio, con su procedencia. */
    StudyAreaItem: {
      id: string;
      name: string;
      kind: components['schemas']['StudyAreaKind'];
      /** Format: double */
      areaSquareMeters: number;
      source: string;
      attribution: string;
      license: null | string;
      note: null | string;
    };
    /** @enum {unknown} */
    StudyAreaKind: 'municipality' | 'district';
    /**
     * @description Un instante de la línea temporal: cuántas estaciones tienen dato, cuántas están vacías o
     *     llenas y qué suman. Operativa: en servicio y prestando o admitiendo devoluciones; es la misma
     *     precedencia que la leyenda de la web (`availability.ts`).
     */
    TimelinePoint: {
      /**
       * Format: date-time
       * @description Instante (UTC) del paso.
       */
      at: string;
      /**
       * Format: int32
       * @description Estaciones con atributos vigentes en ese instante.
       */
      stationsKnown: number;
      /**
       * Format: int32
       * @description Estaciones con observación dentro de la tolerancia (misma regla que el mapa).
       */
      stationsWithData: number;
      /**
       * Format: int32
       * @description De ellas, las operativas con los dos recuentos: las que se suman.
       */
      stationsCounted: number;
      /**
       * Format: int32
       * @description Operativas sin bicis.
       */
      stationsEmpty: number;
      /**
       * Format: int32
       * @description Operativas con bicis y sin anclajes libres.
       */
      stationsFull: number;
      /**
       * Format: int32
       * @description Bicis disponibles en las estaciones contadas; nula si no se cuenta ninguna.
       */
      bikesAvailable: null | number;
      /**
       * Format: int32
       * @description Anclajes libres en las estaciones contadas; nula si no se cuenta ninguna.
       */
      docksAvailable: null | number;
      /**
       * Format: int32
       * @description De las contadas, las que publican cuántas eléctricas tienen: las que suman en EbikesAvailable.
       */
      stationsCountedEbikes: number;
      /**
       * Format: int32
       * @description Bicis eléctricas en esas estaciones; nula si ninguna lo publica. Si no son todas las contadas, no es el total de la red.
       */
      ebikesAvailable: null | number;
    };
    /** @description Línea temporal de una fuente. */
    TimelineResponse: {
      /** @description Fuente consultada, con su tipo. */
      source: components['schemas']['SourceRef'];
      /**
       * Format: date-time
       * @description Primer paso, alineado a la rejilla (UTC).
       */
      from: string;
      /**
       * Format: date-time
       * @description Último paso, alineado a la rejilla (UTC).
       */
      to: string;
      /**
       * Format: int32
       * @description Minutos entre pasos.
       */
      stepMinutes: number;
      /**
       * Format: int32
       * @description Antigüedad máxima de una observación para contar como dato.
       */
      toleranceMinutes: number;
      /** @description Un punto por paso, de From a To. */
      points: components['schemas']['TimelinePoint'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ListSources: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceSummary'][];
        };
      };
    };
  };
  ListIngestions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Identificador de la fuente. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IngestionsResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetTimeline: {
    parameters: {
      query?: {
        /** @description Inicio ISO 8601 con zona. Sin from ni to: las últimas 24 h con datos de la fuente. */
        from?: string;
        /** @description Fin ISO 8601 con zona (incluido). */
        to?: string;
        /** @description Paso en minutos: 5, 10, 15, 30 o 60. Por defecto, 5. */
        step?: number;
      };
      header?: never;
      path: {
        /** @description Identificador de la fuente. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TimelineResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetFrames: {
    parameters: {
      query?: {
        /** @description Primer paso, ISO 8601 con zona. Se alinea hacia atrás a la rejilla del paso. */
        from?: string;
        /** @description Paso en minutos: 5, 10, 15, 30 o 60. Por defecto, 5. */
        step?: number;
      };
      header?: never;
      path: {
        /** @description Identificador de la fuente. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FramesResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  ListStudyAreas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudyAreaItem'][];
        };
      };
    };
  };
  ComputeCoverage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CoverageRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CoverageResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  ListStations: {
    parameters: {
      query?: {
        /** @description Obligatorio. Identificador de la fuente (ver GET /api/sources). */
        source?: string;
        /** @description Opcional. Zona minLon,minLat,maxLon,maxLat en grados WGS84 (máximo 1° de lado). */
        bbox?: string;
        /** @description Opcional. Instante ISO 8601 con zona explícita. Sin él: fuente sintética, final de sus datos; fuente observada, ahora. La respuesta lo indica en atBasis. */
        at?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StationsResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetStation: {
    parameters: {
      query?: {
        /** @description Opcional. Instante ISO 8601 con zona explícita. Sin él: fuente sintética, final de sus datos; fuente observada, ahora. La respuesta lo indica en atBasis. */
        at?: string;
      };
      header?: never;
      path: {
        /** @description Identificador interno de la estación. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StationDetailResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetStationPattern: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Identificador interno de la estación. */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StationPatternResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
}
